let lang = "en";
if (localStorage.getItem("VoidfallLang")) {
    lang = localStorage.getItem("VoidfallLang");
}

const langStrings = {
    "en": {
        appTitle: "Voidfall Helper",
        appSubtitle: "House randomizer, tech tableau generator, and combat calculator.",
        numOfPlayers: "# of players",
        typeOfGame: "Type of game",
        solo: "Solo",
        cooperative: "Cooperative",
        competitive: "Competitive",
        scenarioOptional: "Scenario (optional)",
        setRandomHouse: "Set random house",
        setRandomHouses: "Set random houses",
        setRandomRecommendedHouses: "Set random recommended houses",
        player: "Player",
        playerName: "Name",
        playerHouse: "House",
        startGame: "Start Game",
        enterNameForEachPlayer: 'Please enter a name for each player.',
        allPlayersChooseHouse: 'For scenarios, all players must have a chosen house.',
        notes: "Notes",
        note1: "If you choose a scenario, the app will generate the fallen houses and tech tableau for you. You'll find it on the bottom of the 'Tech' page after starting a game.",
        note2: "Keep track of players' tech during the game on the Tech page. Tech powers are then included in the calculations.",
        note3: "If you are using Carriers, and they deploy Corvettes, simply increase the Corvette count in the calculator before running the calculation. The app does not automatically deploy Corvettes from Carriers.",
        note4: "The app shows all possible outcomes, except for variations where you obviously should recall Corvettes but recall something else instead.",
        note5: "Once you have calculated once, any changes to fleet power will auto-recalculate unless you change the invader/defender.",
        notAffiliated: "Not affiliated with Mindclash Games",
        scenarioTutorial: 'Tutorial',
        scenarioS01: 'First Stand',
        scenarioS02: 'And One For All',
        scenarioS03: 'Darkest Hour',
        scenarioS04: 'Ancient Secrets',
        scenarioS05: 'Devil’s Triangle',
        scenarioS06: 'When Darkness Fades',
        scenarioS07: 'Today Is Not The Day',
        scenarioS08: 'Fall Of Civilization',
        scenarioC01: 'Second Genesis',
        scenarioC02: 'For Peace and Prosperity',
        scenarioC03: 'Foundations of the Future',
        scenarioC04: 'Novarchon Legacy',
        scenarioC05: 'Art of War',
        scenarioC06: 'Whirling Destinies',
        scenarioC07: 'Through the Altered Space',
        scenarioC08: 'Echoes of the Past',
        scenarioC09: 'Bastion of Resistance',
        scenarioC10: 'Kingdom Come',
        scenarioC11: 'Fractures of Space',
        techCybernetics: 'Cybernetics',
        techCombatReplicators: 'Combat Replicators',
        techDreadnoughts: 'Dreadnoughts',
        techDecontaminationChambers: 'Decontamination Chambers',
        techNeuralMatrix: 'Neural Matrix',
        techTerraforming: 'Terraforming',
        techEscapePods: 'Escape Pods',
        techShields: 'Shields',
        techHyperdrive: 'Hyperdrive',
        techTacticalTransports: 'Tactical Transports',
        techCloning: 'Cloning',
        techDestroyers: 'Destroyers',
        techArkShips: 'Ark Ships',
        techCarriers: 'Carriers',
        techAutonomousDrones: 'Autonomous Drones',
        techCentralSurveillance: 'Central Surveillance',
        techDataRefinery: 'Data Refinery',
        techDeepSpaceMissiles: 'Deep Space Missiles',
        techEnergyCells: 'Energy Cells',
        techSentries: 'Sentries',
        techStarbases: 'Starbases',
        techTargeting: 'Targeting',
        techTorpedoes: 'Torpedoes',
        techTradeNexus: 'Trade Nexus',
        fleetCorvette: 'Corvette',
        fleetDestroyer: 'Destroyer',
        fleetDreadnought: 'Dreadnought',
        fleetCarrier: 'Carrier',
        fleetSentry: 'Sentry',
        fleetVoidborn: 'Voidborn',
        fleetSectorDefense: 'Sector Defense',
        fleetStarbase: 'Starbase',
        fleetCorvettePlural: 'Corvettes',
        fleetDestroyerPlural: 'Destroyers',
        fleetDreadnoughtPlural: 'Dreadnoughts',
        fleetCarrierPlural: 'Carriers',
        fleetSentryPlural: 'Sentries',
        fleetVoidbornPlural: 'Voidborn',
        fleetSectorDefensePlural: 'Sector Defenses',
        fleetStarbasesPlural: 'Starbases',
        newGame: 'New Game',
        confirmNewGame: 'Are you sure you want to clear the app and start a new game?',
        techLink: 'Tech',
        calcLink: 'Calc',
        technologies: 'Technologies',
        viewTableau: 'View Tableau',
        playerCombatTech: 'Player Combat Tech',
        tableau: 'Tableau',
        tableauExplanation: 'An initial tech tableau generated for \'${0}\' and the chosen player houses.',
        techBasic: 'Basic',
        techImproved: 'Improved',
        tutorialTechHouses: 'Tutorial Tech Houses',
        fallenHouses: 'Fallen Houses (in random order)',
        cardWithVP: 'Card w/ VP?',
        cardWithoutVP: 'Card w/out VP?',
        yes: 'Yes',
        no: 'No',
        calculator: 'Calculator',
        invader: 'Invader',
        defender: 'Defender',
        outcomes: 'Outcomes',
        carrierMessage: 'If Invader Carriers deploy Corvettes, increase Corvettes above.',
        returnTradeTokenDrones: 'Return Trade Token (Drones)?',
        useBombard: 'Use Bombard (Nervo)?',
        bombardApproachAbs: 'Bombard Approach Abs',
        bombardSalvoAbs: 'Bombard Salvo Abs',
        spendEnergyDSM: 'Spend 1 Energy (Deep Space Missiles)?',
        adjacentSectorsWithShipyards: 'Adjacent Sectors w/ Shipyards',
        adjacentSectorsWithStarbases: 'Adjacent Sectors w/ Starbases',
        initiativeWarCard: '+5 Initiative (War card)',
        approachAbsWarCard: '+1 Approach absorption (War card)',
        salvoAbsWarCardEasy: '+1 Salvo absorption (War card - Easy)',
        salvoAbsWarCardHard: '+2 Salvo absorption (War card - Norm/Hard)',
        salvoAbsCycle2EventH: '+X Salvo absorption (Cycle 2 - Event H)',
        salvoAbsCycle2EventHWithDetail: '+${0} Salvo absorption (Cycle 2 - Event H)',
        calculateOutcomes: 'Calculate Outcomes',
        swap: 'Swap',
        multipleOutcomes: 'NOTE: There are multiple possible outcomes. Check details to determine which will happen in your game.',
        collapse: 'Collapse',
        expand: 'Expand',
        share: 'Share',
        combatSummaryCopied: 'Combat summary copied to clipboard.',
        invaderWins: 'Invader (${0}) Wins',
        invaderWinsNoDetail: 'Invader Wins',
        defenderWins: 'Defender (${0}) Wins',
        defenderWinsNoDetail: 'Defender Wins',
        ties: 'Ties',
        finalFleet: 'Final Fleet (v${0})',
        combatVersion: 'Combat v${0}',
        approach: 'Approach',
        salvo: 'Salvo',
        improvedShields: 'Improved Shields',
        bombard: 'Bombard',
        warCard: 'War Card',
        warCardEasy: 'War Card - Easy',
        warCardNormalHard: 'War Card - Normal/Hard',
        warCardHard: 'War Card - Hard',
        cycle2EventH: 'Cycle 2 - Event H',
        drones: 'Drones',
        improvedDrones: 'Improved Drones',
        improvedDSMs: 'Improved Deep Space Missiles',
        improvedTorpedoes: 'Improved Torpedoes',
        improvedDestroyers: 'Improved Destroyers',
        plusInvaderAbsorption: '+${0} Invader Abs (${1})',
        plusDefenderAbsorption: '+${0} Defender Abs (${1})',
        plusInvaderDamage: '+${0} Invader Dmg (${1})',
        plusDefenderDamage: '+${0} Defender Dmg (${1})',
        invaderFleetLost: '${0} invader ${1} lost.',
        defenderFleetLost: '${0} defender ${1} lost.',
        invaderDmgFullyAbsorbed: '${0} Invader dmg fully absorbed by Defender.',
        defenderDmgFullyAbsorbed: '${0} Defender dmg fully absorbed by Invader.',
        invaderNoApproachDmg: 'Invader has no approach dmg capability.',
        defenderNoApproachDmg: 'Defender has no approach dmg capability.',
        invaderDefenderSimul: 'Invader and Defender hit simultaneously',
        invaderHitsFirst: 'Invader hits first',
        defenderHitsSecond: 'Defender hits second',
        defenderHitsFirst: 'Defender hits first',
        invaderHitsSecond: 'Invader hits second',
        defenderNoSalvoDmg: 'Defender has no salvo dmg capability.',
        defenderAbsorbedAllDmg: 'Defender absorbed all damage.',
        invaderAbsorbedAllDmg: 'Invader absorbed all damage.'
    },
    "fr": {
        appTitle: "Assistant de Voidfall",
        appSubtitle: "Sélection aléatoire de maisons, génération de tableau des technologies, et calcul de combat.",
        numOfPlayers: "Nombre de joueurs",
        typeOfGame: "Type de jeu",
        solo: "Solo",
        cooperative: "Coopératif",
        competitive: "Compétitif",
        scenarioOptional: "Scénario (optionnel)",
        setRandomHouse: "Définir maison aléatoire",
        setRandomHouses: "Définir maisons aléatoires",
        setRandomRecommendedHouses: "Définir maisons recommandées aléatoires",
        player: "Joueur",
        playerName: "Nom",
        playerHouse: "Maison",
        startGame: "Démarrer la partie",
        enterNameForEachPlayer: 'Veuillez saisir un nom pour chaque joueur.',
        allPlayersChooseHouse: 'Pour les scénarios, tous les joueurs doivent avoir choisi une maison.',
        notes: "Notes",
        note1: "Si vous choisissez un scénario, l'application générera pour vous les maisons déchues et le tableau des technologies. Vous les trouverez en bas de la page 'Tech' après avoir démarré une partie.",
        note2: "Suivez les technologies des joueurs pendant la partie sur la page Tech. Les capacités des technologies sont ensuite incluses dans les calculs.",
        note3: "Si vous utilisez des Porte-Vaisseaux et qu'ils déploient des Corvettes, augmentez simplement le nombre de Corvettes dans le calculateur avant d'exécuter le calcul. L'application ne déploie pas automatiquement les Corvettes à partir des Porte-Vaisseaux.",
        note4: "L'application affiche tous les résultats possibles, à l'exception des variantes où vous devriez évidemment rappeler des Corvettes mais rappelez autre chose à la place.",
        note5: "Une fois que vous avez effectué un calcul, tout changement de la puissance de la flotte recalculera automatiquement le résultat, à moins que vous ne changiez l'envahisseur/défenseur.",
        notAffiliated: "Non affilié à Mindclash Games",
        scenarioTutorial: 'Tutoriel',
        scenarioS01: 'Première ligne',
        scenarioS02: 'Ultime résistance',
        scenarioS03: 'Les heures sombres',
        scenarioS04: 'Secrets anciens',
        scenarioS05: 'Le triangle du Diable',
        scenarioS06: 'L’obscure clarté',
        scenarioS07: 'Ce jour n’est pas arrivé',
        scenarioS08: 'La chute d’une civilisation',
        scenarioC01: 'Seconde genèse',
        scenarioC02: 'Paix et prospérité',
        scenarioC03: 'Les fondations du futur',
        scenarioC04: 'L’héritage des Novarques',
        scenarioC05: 'L’art de la guerre',
        scenarioC06: 'Tempêtes cosmiques',
        scenarioC07: 'À travers les cieux',
        scenarioC08: 'Les échos du passé',
        scenarioC09: 'Le bastion de la résistance',
        scenarioC10: 'Le royaume',
        scenarioC11: 'Fractures spatiales',
        techCybernetics: 'Cybernétique',
        techCombatReplicators: 'Réplicateurs de Combat',
        techDreadnoughts: 'Cuirassés',
        techDecontaminationChambers: 'Chambres de Décontamination',
        techNeuralMatrix: 'Matrice Neuronale',
        techTerraforming: 'Terraformation',
        techEscapePods: 'Nacelles',
        techShields: 'Boucliers',
        techHyperdrive: 'Hyperpropulsion',
        techTacticalTransports: 'Transports Tactiques',
        techCloning: 'Clonage',
        techDestroyers: 'Destroyers',
        techArkShips: 'Vaisseaux-Arches',
        techCarriers: 'Porte-Vaisseaux',
        techAutonomousDrones: 'Drones Autonomes',
        techCentralSurveillance: 'Surveillance Centrale',
        techDataRefinery: 'Scanner de Récupération',
        techDeepSpaceMissiles: 'Missiles Longue Portée',
        techEnergyCells: 'Cellules Énergétiques',
        techSentries: 'Sentinelles',
        techStarbases: 'Bases Stellaires',
        techTargeting: 'Ciblage',
        techTorpedoes: 'Torpilles',
        techTradeNexus: 'Purificateur',
        fleetCorvette: 'Corvette',
        fleetDestroyer: 'Destroyer',
        fleetDreadnought: 'Cuirassé',
        fleetCarrier: 'Porte-Vaisseaux',
        fleetSentry: 'Sentinelle',
        fleetVoidborn: 'Néant',
        fleetSectorDefense: 'Défense de Secteur',
        fleetStarbase: 'Base Stellaire',
        fleetCorvettePlural: 'Corvettes',
        fleetDestroyerPlural: 'Destroyers',
        fleetDreadnoughtPlural: 'Cuirassés',
        fleetCarrierPlural: 'Porte-Vaisseaux',
        fleetSentryPlural: 'Sentinelles',
        fleetVoidbornPlural: 'Néant',
        fleetSectorDefensePlural: 'Défenses de Secteur',
        fleetStarbasesPlural: 'Bases Stellaires',
        newGame: 'Nouveau',
        confirmNewGame: 'Êtes-vous sûr de vouloir réinitialiser l\'application et commencer une nouvelle partie?',
        techLink: 'Tech',
        calcLink: 'Calc',
        technologies: 'Technologies',
        viewTableau: 'Voir le Tableau',
        playerCombatTech: 'Tech de Combat du Joueur',
        tableau: 'Tableau',
        tableauExplanation: 'Un tableau des technologies initial généré pour \'${0}\' et les maisons choisies par les joueurs.',
        techBasic: 'Base',
        techImproved: 'Améliorée',
        tutorialTechHouses: 'Maisons Tech du Tutoriel',
        fallenHouses: 'Maisons Déchues (dans un ordre aléatoire)',
        cardWithVP: 'Carte avec VP ?',
        cardWithoutVP: 'Carte sans VP ?',
        yes: 'Oui',
        no: 'Non',
        calculator: 'Calculateur',
        invader: 'Envahisseur',
        defender: 'Défenseur',
        outcomes: 'Résultats',
        carrierMessage: 'Si les Porte-Vaisseaux de l\'Envahisseur déploient des Corvettes, augmentez le nombre de Corvettes ci-dessus.',
        returnTradeTokenDrones: 'Rendre le jeton de commerce (Drones) ?',
        useBombard: 'Utiliser Bombardement (Nervo) ?',
        bombardApproachAbs: 'Approche de Bombardement Abs.',
        bombardSalvoAbs: 'Absorption de Salve de Bombardement',
        spendEnergyDSM: 'Dépenser 1 Énergie (Missiles Longue Portée) ?',
        adjacentSectorsWithShipyards: 'Secteurs adjacents avec Chantier Naval',
        adjacentSectorsWithStarbases: 'Secteurs adjacents avec Base Stellaire',
        initiativeWarCard: '+5 Initiative (carte de Guerre)',
        approachAbsWarCard: '+1 Absorption d\'Approche (carte de Guerre)',
        salvoAbsWarCardEasy: '+1 Absorption de Salve (carte de Guerre - Facile)',
        salvoAbsWarCardHard: '+2 Absorption de Salve (carte de Guerre - Normal/Difficile)',
        salvoAbsCycle2EventH: '+X Absorption de Salve (Cycle 2 - Événement H)',
        salvoAbsCycle2EventHWithDetail: '+${0} Absorption de Salve (Cycle 2 - Événement H)',
        calculateOutcomes: 'Calculer les résultats',
        swap: 'Échanger',
        multipleOutcomes: 'NOTE : Il y a plusieurs résultats possibles. Vérifiez les détails pour déterminer lequel se produira dans votre partie.',
        collapse: 'Réduire',
        expand: 'Déplier',
        share: 'Partager',
        combatSummaryCopied: 'Résumé du combat copié dans le presse-papiers.',
        invaderWins: 'L\'Envahisseur (${0}) gagne',
        invaderWinsNoDetail: 'L\'Envahisseur gagne',
        defenderWins: 'Le Défenseur (${0}) gagne',
        defenderWinsNoDetail: 'Le Défenseur gagne',
        ties: 'Égalités',
        finalFleet: 'Flotte finale (v${0})',
        combatVersion: 'Combat v${0}',
        approach: 'Approche',
        salvo: 'Salve',
        improvedShields: 'Boucliers Améliorés',
        bombard: 'Bombardement',
        warCard: 'Carte de Guerre',
        warCardEasy: 'Carte de Guerre - Facile',
        warCardNormalHard: 'Carte de Guerre - Normal/Difficile',
        warCardHard: 'Carte de Guerre - Difficile',
        cycle2EventH: 'Cycle 2 - Événement H',
        drones: 'Drones',
        improvedDrones: 'Drones Améliorés',
        improvedDSMs: 'Missiles Longue Portée Améliorés',
        improvedTorpedoes: 'Torpilles Améliorées',
        improvedDestroyers: 'Destroyers Améliorés',
        plusInvaderAbsorption: '+${0} Abs. Envahisseur (${1})',
        plusDefenderAbsorption: '+${0} Abs. Défenseur (${1})',
        plusInvaderDamage: '+${0} Dég. Envahisseur (${1})',
        plusDefenderDamage: '+${0} Dég. Défenseur (${1})',
        invaderFleetLost: '${0} ${1} de l’Envahisseur perdu(e)(s).',
        defenderFleetLost: '${0} ${1} du Défenseur perdu(e)(s).',
        invaderDmgFullyAbsorbed: '${0} Dég. Envahisseur entièrement absorbés par le Défenseur.',
        defenderDmgFullyAbsorbed: '${0} Dég. Défenseur entièrement absorbés par l\'Envahisseur.',
        invaderNoApproachDmg: 'L\'Envahisseur n\'a pas de capacité de dégâts d\'approche.',
        defenderNoApproachDmg: 'Le Défenseur n\'a pas de capacité de dégâts d\'approche.',
        invaderDefenderSimul: 'L\'Envahisseur et le Défenseur frappent simultanément',
        invaderHitsFirst: 'L\'Envahisseur frappe le premier',
        defenderHitsSecond: 'Le Défenseur frappe le second',
        defenderHitsFirst: 'Le Défenseur frappe le premier',
        invaderHitsSecond: 'L\'Envahisseur frappe le second',
        defenderNoSalvoDmg: 'Le Défenseur n\'a pas de capacité de dégâts de salve.',
        defenderAbsorbedAllDmg: 'Le Défenseur a absorbé tous les dégâts.',
        invaderAbsorbedAllDmg: 'L\'Envahisseur a absorbé tous les dégâts.'
    },
    "de": {
        appTitle: "Voidfall Helfer",
        appSubtitle: "Hauszufallsgenerator, Tech-Tableau-Generator und Kampfrechner.",
        numOfPlayers: "Anzahl der Spieler",
        typeOfGame: "Spieltyp",
        solo: "Solo",
        cooperative: "Kooperativ",
        competitive: "Wettbewerbsfähig",
        scenarioOptional: "Szenario (optional)",
        setRandomHouse: "Zufälliges Haus festlegen",
        setRandomHouses: "Zufällige Häuser festlegen",
        setRandomRecommendedHouses: "Zufällig empfohlene Häuser festlegen",
        player: "Spieler",
        playerName: "Name",
        playerHouse: "Haus",
        startGame: "Spiel starten",
        enterNameForEachPlayer: 'Bitte geben Sie für jeden Spieler einen Namen ein.',
        allPlayersChooseHouse: 'Für Szenarien müssen alle Spieler ein Haus gewählt haben.',
        notes: "Notizen",
        note1: "Wenn Sie ein Szenario wählen, generiert die App für Sie die gefallenen Häuser und das Tech-Tableau. Sie finden es unten auf der 'Tech'-Seite nach Spielstart.",
        note2: "Verfolgen Sie während des Spiels die Tech der Spieler auf der Tech-Seite. Tech-Kräfte werden dann in die Berechnungen einbezogen.",
        note3: "Wenn Sie Träger verwenden und diese Korvetten einsetzen, erhöhen Sie einfach die Anzahl der Korvetten im Rechner, bevor Sie die Berechnung ausführen. Die App setzt nicht automatisch Korvetten von Trägern ein.",
        note4: "Die App zeigt alle möglichen Ergebnisse an, außer Variationen, bei denen Sie offensichtlich Korvetten zurückrufen sollten, aber stattdessen etwas anderes zurückrufen.",
        note5: "Sobald Sie einmal berechnet haben, wird jede Änderung der Flottenstärke automatisch neu berechnet, es sei denn, Sie ändern den Angreifer/Verteidiger.",
        notAffiliated: "Nicht verbunden mit Mindclash Games",
        scenarioTutorial: 'Tutorial',
        scenarioS01: 'Erste Instanz',
        scenarioS02: 'Eines Für Alle',
        scenarioS03: 'Dunkelste Stunde',
        scenarioS04: 'Antike Geheimnisse',
        scenarioS05: 'Teufelsdreieck',
        scenarioS06: 'Verblasende Finsternis',
        scenarioS07: 'Noch Nicht Heute',
        scenarioS08: 'Niedergang Der Zivilisation',
        scenarioC01: 'Zweite Genesis',
        scenarioC02: 'Für Frieden und Wohlstand',
        scenarioC03: 'Grundlagen der Zukunft',
        scenarioC04: 'Vermächtnis der Novarchen',
        scenarioC05: 'Kriegskunst',
        scenarioC06: 'Schicksalsstrudel',
        scenarioC07: 'Durch Die Veränderten Weiten',
        scenarioC08: 'Echos der Vergangenheit',
        scenarioC09: 'Bastion Des Widerstands',
        scenarioC10: 'Aufstieg Des Königreichs',
        scenarioC11: 'Frakturen Im All',
        techCybernetics: 'Autonome Drohnen',
        techCombatReplicators: 'Datenraffinerie',
        techDreadnoughts: 'Bergungsscanner',
        techDecontaminationChambers: 'Dekontaminationskammern',
        techNeuralMatrix: 'Energiezellen',
        techTerraforming: 'Hyperantrieb',
        techEscapePods: 'Handelsnexus',
        techShields: 'Kampfreplikatoren',
        techHyperdrive: 'Klonen',
        techTacticalTransports: 'Kybernetik',
        techCloning: 'Kolonieschiffe',
        techDestroyers: 'Läuterer',
        techArkShips: 'Orbitale Häfen',
        techCarriers: 'Robotik',
        techAutonomousDrones: 'Schilde',
        techCentralSurveillance: 'Sternenbasen',
        techDataRefinery: 'Schlächter',
        techDeepSpaceMissiles: 'Taktische Transporte',
        techEnergyCells: 'Terraformen',
        techSentries: 'Träger',
        techStarbases: 'Torpedos',
        techTargeting: 'Wächter',
        techTorpedoes: 'Weltraumgeschosse',
        techTradeNexus: 'Zerstörer',
        fleetCorvette: 'Korvette',
        fleetDestroyer: 'Zerstörer',
        fleetDreadnought: 'Schlachtschiff',
        fleetCarrier: 'Träger',
        fleetSentry: 'Wächter',
        fleetVoidborn: 'Leere',
        fleetSectorDefense: 'Sektor Verteidigung',
        fleetStarbase: 'Sternenbasis',
        fleetCorvettePlural: 'Korvetten',
        fleetDestroyerPlural: 'Zerstörer',
        fleetDreadnoughtPlural: 'Schlachtschiffe',
        fleetCarrierPlural: 'Träger',
        fleetSentryPlural: 'Wächter',
        fleetVoidbornPlural: 'Leere',
        fleetSectorDefensePlural: 'Sektor Verteidigungen',
        fleetStarbasesPlural: 'Sternenbasen',
        newGame: 'Neues Spiel',
        confirmNewGame: 'Sind Sie sicher, dass Sie die App löschen und ein neues Spiel starten möchten?',
        techLink: 'Technik',
        calcLink: 'Rechner',
        technologies: 'Technologien',
        viewTableau: 'Tableau anzeigen',
        playerCombatTech: 'Spieler Kampftechnologie',
        tableau: 'Tableau',
        tableauExplanation: 'Ein anfängliches Technik-Tableau generiert für \'${0}\' und die gewählten Spielerhäuser.',
        techBasic: 'Grundlegend',
        techImproved: 'Verbessert',
        tutorialTechHouses: 'Tutorial Technologiehäuser',
        fallenHouses: 'Gefallene Häuser (in zufälliger Reihenfolge)',
        cardWithVP: 'Karte mit Siegpunkten?',
        cardWithoutVP: 'Karte ohne Siegpunkte?',
        yes: 'Ja',
        no: 'Nein',
        calculator: 'Rechner',
        invader: 'Invasor',
        defender: 'Verteidiger',
        outcomes: 'Ergebnisse',
        carrierMessage: 'Wenn Invasor Träger Korvetten einsetzt, erhöhe die Anzahl der Korvetten entsprechend.',
        returnTradeTokenDrones: 'Handelsmarke zurückgeben (Drohnen)?',
        useBombard: 'Bombardieren verwenden (Nervo)?',
        bombardApproachAbs: 'Bombardierungs-Annäherungsabsorption',
        bombardSalvoAbs: 'Bombardierungs-Salvenabsorption',
        spendEnergyDSM: '1 Energie ausgeben (Tiefraumraketen)?',
        adjacentSectorsWithShipyards: 'Angrenzende Sektoren mit Werften',
        adjacentSectorsWithStarbases: 'Angrenzende Sektoren mit Sternenbasen',
        initiativeWarCard: '+5 Initiative (Kriegskarte)',
        approachAbsWarCard: '+1 Annäherungsabsorption (Kriegskarte)',
        salvoAbsWarCardEasy: '+1 Salvenabsorption (Kriegskarte - Einfach)',
        salvoAbsWarCardHard: '+2 Salvenabsorption (Kriegskarte - Normal/Schwer)',
        salvoAbsCycle2EventH: '+X Salvenabsorption (Zyklus 2 - Ereignis H)',
        salvoAbsCycle2EventHWithDetail: '+${0} Salvenabsorption (Zyklus 2 - Ereignis H)',
        calculateOutcomes: 'Ergebnisse berechnen',
        swap: 'Tauschen',
        multipleOutcomes: 'HINWEIS: Es gibt mehrere mögliche Ergebnisse. Überprüfen Sie die Details, um festzustellen, was in Ihrem Spiel passieren wird.',
        collapse: 'Einklappen',
        expand: 'Ausklappen',
        share: 'Teilen',
        combatSummaryCopied: 'Kampfzusammenfassung in die Zwischenablage kopiert.',
        invaderWins: 'Invasor (${0}) gewinnt',
        invaderWinsNoDetail: 'Invasor gewinnt',
        defenderWins: 'Verteidiger (${0}) gewinnt',
        defenderWinsNoDetail: 'Verteidiger gewinnt',
        ties: 'Unentschieden',
        finalFleet: 'Endgültige Flotte (v${0})',
        combatVersion: 'Kampf v${0}',
        approach: 'Annäherung',
        salvo: 'Salve',
        improvedShields: 'Verbesserte Schilde',
        bombard: 'Bombardieren',
        warCard: 'Kriegskarte',
        warCardEasy: 'Kriegskarte - Einfach',
        warCardNormalHard: 'Kriegskarte - Normal/Schwer',
        warCardHard: 'Kriegskarte - Schwer',
        cycle2EventH: 'Zyklus 2 - Ereignis H',
        drones: 'Drohnen',
        improvedDrones: 'Verbesserte Drohnen',
        improvedDSMs: 'Verbesserte Tiefraumraketen',
        improvedTorpedoes: 'Verbesserte Torpedos',
        improvedDestroyers: 'Verbesserte Zerstörer',
        plusInvaderAbsorption: '+${0} Invasor Abs (${1})',
        plusDefenderAbsorption: '+${0} Verteidiger Abs (${1})',
        plusInvaderDamage: '+${0} Invasor Schaden (${1})',
        plusDefenderDamage: '+${0} Verteidiger Schaden (${1})',
        invaderFleetLost: '${0} Invasor ${1} verloren.',
        defenderFleetLost: '${0} Verteidiger ${1} verloren.',
        invaderDmgFullyAbsorbed: '${0} Invasor Schaden vollständig von Verteidiger absorbiert.',
        defenderDmgFullyAbsorbed: '${0} Verteidiger Schaden vollständig von Invasor absorbiert.',
        invaderNoApproachDmg: 'Invasor hat keine Annäherungsschadensfähigkeit.',
        defenderNoApproachDmg: 'Verteidiger hat keine Annäherungsschadensfähigkeit.',
        invaderDefenderSimul: 'Invasor und Verteidiger treffen gleichzeitig',
        invaderHitsFirst: 'Invasor trifft zuerst',
        defenderHitsSecond: 'Verteidiger trifft als Zweiter',
        defenderHitsFirst: 'Verteidiger trifft zuerst',
        invaderHitsSecond: 'Invasor trifft als Zweiter',
        defenderNoSalvoDmg: 'Verteidiger hat keine Salvenschadensfähigkeit.',
        defenderAbsorbedAllDmg: 'Verteidiger absorbiert allen Schaden.',
        invaderAbsorbedAllDmg: 'Invasor absorbiert allen Schaden.'
    }
}