let lang = "en";
if (localStorage.getItem("VoidfallLang")) {
    lang = localStorage.getItem("VoidfallLang");
}

const langStrings = {
    "en": {
        appTitle: "Voidfall Helper",
        appSubtitle: "House randomizer, tech tableau generator, and combat calculator.",
        numOfPlayers: "# of players",
        typeOfGame: "Type of game",
        solo: "Solo",
        cooperative: "Cooperative",
        competitive: "Competitive",
        scenarioOptional: "Scenario (optional)",
        setRandomHouse: "Set random house",
        setRandomHouses: "Set random houses",
        setRandomRecommendedHouses: "Set random recommended houses",
        player: "Player",
        playerName: "Name",
        playerHouse: "House",
        startGame: "Start Game",
        notes: "Notes",
        note1: "If you choose a scenario, the app will generate the fallen houses and tech tableau for you. You'll find it on the bottom of the 'Tech' page after starting a game.",
        note2: "Keep track of players' tech during the game on the Tech page. Tech powers are then included in the calculations.",
        note3: "If you are using Carriers, and they deploy Corvettes, simply increase the Corvette count in the calculator before running the calculation. The app does not automatically deploy Corvettes from Carriers.",
        note4: "The app shows all possible outcomes, except for variations where you obviously should recall Corvettes but recall something else instead.",
        note5: "Once you have calculated once, any changes to fleet power will auto-recalculate unless you change the invader/defender.",
        notAffiliated: "Not affiliated with Mindclash Games",
        scenarioTutorial: 'Tutorial',
        scenarioS01: 'First Stand',
        scenarioS02: 'And One For All',
        scenarioS03: 'Darkest Hour',
        scenarioS04: 'Ancient Secrets',
        scenarioS05: 'Devil’s Triangle',
        scenarioS06: 'When Darkness Fades',
        scenarioS07: 'Today Is Not The Day',
        scenarioS08: 'Fall Of Civilization',
        scenarioC01: 'Second Genesis',
        scenarioC02: 'For Peace and Prosperity',
        scenarioC03: 'Foundations of the Future',
        scenarioC04: 'Novarchon Legacy',
        scenarioC05: 'Art of War',
        scenarioC06: 'Whirling Destinies',
        scenarioC07: 'Through the Altered Space',
        scenarioC08: 'Echoes of the Past',
        scenarioC09: 'Bastion of Resistance',
        scenarioC10: 'Kingdom Come',
        scenarioC11: 'Fractures of Space',
        techCybernetics: 'Cybernetics',
        techCombatReplicators: 'Combat Replicators',
        techDreadnoughts: 'Dreadnoughts',
        techDecontaminationChambers: 'Decontamination Chambers',
        techNeuralMatrix: 'Neural Matrix',
        techTerraforming: 'Terraforming',
        techEscapePods: 'Escape Pods',
        techShields: 'Shields',
        techHyperdrive: 'Hyperdrive',
        techTacticalTransports: 'Tactical Transports',
        techCloning: 'Cloning',
        techDestroyers: 'Destroyers',
        techArkShips: 'Ark Ships',
        techCarriers: 'Carriers',
        techAutonomousDrones: 'Autonomous Drones',
        techCentralSurveillance: 'Central Surveillance',
        techDataRefinery: 'Data Refinery',
        techDeepSpaceMissiles: 'Deep Space Missiles',
        techEnergyCells: 'Energy Cells',
        techSentries: 'Sentries',
        techStarbases: 'Starbases',
        techTargeting: 'Targeting',
        techTorpedoes: 'Torpedoes',
        techTradeNexus: 'Trade Nexus',
        fleetCorvette: 'Corvette',
        fleetDestroyer: 'Destroyer',
        fleetDreadnought: 'Dreadnought',
        fleetCarrier: 'Carrier',
        fleetSentry: 'Sentry',
        fleetVoidborn: 'Voidborn',
        fleetSectorDefense: 'Sector Defense',
        fleetStarbase: 'Starbase',
        fleetCorvettePlural: 'Corvettes',
        fleetDestroyerPlural: 'Destroyers',
        fleetDreadnoughtPlural: 'Dreadnoughts',
        fleetCarrierPlural: 'Carriers',
        fleetSentryPlural: 'Sentries',
        fleetVoidbornPlural: 'Voidborn',
        fleetSectorDefensePlural: 'Sector Defenses',
        fleetStarbasesPlural: 'Starbases',
        newGame: 'New Game',
        techLink: 'Tech',
        calcLink: 'Calc',
        technologies: 'Technologies',
        viewTableau: 'View Tableau',
        playerCombatTech: 'Player Combat Tech',
        tableau: 'Tableau',
        tableauExplanation: 'An initial tech tableau generated for \'${0}\' and the chosen player houses.',
        techBasic: 'Basic',
        techImproved: 'Improved',
        tutorialTechHouses: 'Tutorial Tech Houses',
        fallenHouses: 'Fallen Houses (in random order)',
        cardWithVP: 'Card w/ VP?',
        cardWithoutVP: 'Card w/out VP?',
        yes: 'Yes',
        no: 'No',
        calculator: 'Calculator',
        invader: 'Invader',
        defender: 'Defender',
        carrierMessage: 'If Invader Carriers deploy Corvettes, increase Corvettes above.',
        returnTradeTokenDrones: 'Return Trade Token (Drones)?',
        useBombard: 'Use Bombard (Nervo)?',
        bombardApproachAbs: 'Bombard Approach Abs',
        bombardSalvoAbs: 'Bombard Salvo Abs',
        spendEnergyDSM: 'Spend 1 Energy (Deep Space Missiles)?',
        adjacentSectorsWithShipyards: 'Adjacent Sectors w/ Shipyards',
        adjacentSectorsWithStarbases: 'Adjacent Sectors w/ Starbases',
        initiativeWarCard: '+5 Initiative (War card)',
        approachAbsWarCard: '+1 Approach absorption (War card)',
        salvoAbsWarCardEasy: '+1 Salvo absorption (War card - Easy)',
        salvoAbsWarCardHard: '+2 Salvo absorption (War card - Norm/Hard)',
        salvoAbsCycle2EventH: '+X Salvo absorption (Cycle 2 - Event H)',
        calculateOutcomes: 'Calculate Outcomes',
        swap: 'Swap',
        multipleOutcomes: 'NOTE: There are multiple possible outcomes. Check details to determine which will happen in your game.',
        collapse: 'Collapse',
        share: 'Share',
        combatSummaryCopied: 'Combat summary copied to clipboard.',
        invaderWins: 'Invader (${0}) Wins',
        finalFleet: 'Final Fleet (v${0})',
        combatVersion: 'Combat v${0}',
        approach: 'Approche',
        salvo: 'Salve',
        improvedAdjective: 'Improved ${0}',
        plusAbsorption: '+${0} ${1} Abs (${2}${3})'
    },
    "fr": {
        appTitle: "Assistant de Voidfall",
        appSubtitle: "Générateur aléatoire de Maisons, créateur de tableau technologique, et calculateur de combat.",
        numOfPlayers: "Nombre de joueurs",
        typeOfGame: "Type de jeu",
        solo: "Solo",
        cooperative: "Coopératif",
        competitive: "Compétitif",
        scenarioOptional: "Scénario (optionnel)",
        setRandomHouse: "Définir maison aléatoire",
        setRandomHouses: "Définir maisons aléatoires",
        setRandomRecommendedHouses: "Définir maisons recommandées aléatoires",
        player: "Joueur",
        playerName: "Nom",
        playerHouse: "Maison",
        startGame: "Démarrer la partie",
        notes: "Notes",
        note1: "Si vous choisissez un scénario, l'application générera pour vous les maisons déchues et le tableau technologique. Vous les trouverez en bas de la page 'Tech' après avoir démarré une partie.",
        note2: "Suivez la technologie des joueurs pendant la partie sur la page Tech. Les pouvoirs technologiques sont ensuite inclus dans les calculs.",
        note3: "Si vous utilisez des Porte-vaisseaux et qu'ils déploient des Corvettes, augmentez simplement le nombre de Corvettes dans le calculateur avant d'exécuter le calcul. L'application ne déploie pas automatiquement les Corvettes à partir des Porte-vaisseaux.",
        note4: "L'application affiche tous les résultats possibles, à l'exception des variantes où vous devriez évidemment rappeler des Corvettes mais rappeler autre chose à la place.",
        note5: "Une fois que vous avez effectué un calcul, tout changement de la puissance de la flotte recalculera automatiquement, à moins que vous ne changiez l'envahisseur/défenseur.",
        notAffiliated: "Non affilié à Mindclash Games",
        scenarioTutorial: 'Tutoriel',
        scenarioS01: 'Première Ligne',
        scenarioS02: 'Ultime Résistance',
        scenarioS03: 'Les Heures Sombres',
        scenarioS04: 'Secrets Anciens',
        scenarioS05: 'Le Triangle Du Diable',
        scenarioS06: 'L’Obscure Clarté',
        scenarioS07: 'Ce Jour N’Est Pas Arrivé',
        scenarioS08: 'La Chute D’Une Civilisation',
        scenarioC01: 'Seconde Genèse',
        scenarioC02: 'Paix et Prospérité',
        scenarioC03: 'Les Fondations du Futur',
        scenarioC04: 'L’Héritage des Novarques',
        scenarioC05: 'L’Art de la Guerre',
        scenarioC06: 'Tempêtes Cosmiques',
        scenarioC07: 'À Travers Les Cieux',
        scenarioC08: 'Les Échos Du Passé',
        scenarioC09: 'Le Bastion de la Résistance',
        scenarioC10: 'Le Royaume',
        scenarioC11: 'Fractures Spatiales',
        techCybernetics: 'Cybernétique',
        techCombatReplicators: 'Réplicateurs De Combat',
        techDreadnoughts: 'Cuirassés',
        techDecontaminationChambers: 'Chambres De Décontamination',
        techNeuralMatrix: 'Matrice Neuronale',
        techTerraforming: 'Terraformation',
        techEscapePods: 'Nacelles',
        techShields: 'Boucliers',
        techHyperdrive: 'Hyperpropulsion',
        techTacticalTransports: 'Transports Tactiques',
        techCloning: 'Clonage',
        techDestroyers: 'Destroyers',
        techArkShips: 'Vaisseaux-Arches',
        techCarriers: 'Porte-Vaisseaux',
        techAutonomousDrones: 'Drones Autonomes',
        techCentralSurveillance: 'Surveillance Centrale',
        techDataRefinery: 'Scanner De Récupération',
        techDeepSpaceMissiles: 'Missiles Longue Portée',
        techEnergyCells: 'Cellules Énergétiques',
        techSentries: 'Sentinelles',
        techStarbases: 'Bases Stellaires',
        techTargeting: 'Ciblage',
        techTorpedoes: 'Torpilles',
        techTradeNexus: 'Purificateur',
        fleetCorvette: 'Corvette',
        fleetDestroyer: 'Destroyer',
        fleetDreadnought: 'Cuirassé',
        fleetCarrier: 'Porte-vaisseaux',
        fleetSentry: 'Sentinelle',
        fleetVoidborn: 'Néant',
        fleetSectorDefense: 'Défense de Secteur',
        fleetStarbase: 'Base Stellaire',
        fleetCorvettePlural: 'Corvettes',
        fleetDestroyerPlural: 'Destroyers',
        fleetDreadnoughtPlural: 'Cuirassés',
        fleetCarrierPlural: 'Porte-vaisseaux',
        fleetSentryPlural: 'Sentinelles',
        fleetVoidbornPlural: 'Néant',
        fleetSectorDefensePlural: 'Défenses de Secteur',
        fleetStarbasesPlural: 'Bases Stellaires',
        newGame: 'Nouveau',
        techLink: 'Tech',
        calcLink: 'Calc',
        technologies: 'Technologies',
        viewTableau: 'Voir le Tableau',
        playerCombatTech: 'Tech de Combat du Joueur',
        tableau: 'Tableau',
        tableauExplanation: 'Un tableau technologique initial généré pour \'${0}\' et les maisons des joueurs choisis.',
        techBasic: 'Basique',
        techImproved: 'Amélioré',
        tutorialTechHouses: 'Maisons Tech du Tutoriel',
        fallenHouses: 'Maisons Déchues (dans un ordre aléatoire)',
        cardWithVP: 'Carte avec VP?',
        cardWithoutVP: 'Carte sans VP?',
        yes: 'Oui',
        no: 'Non',
        calculator: 'Calculateur',
        invader: 'Envahisseur',
        defender: 'Défenseur',
        carrierMessage: 'Si les Porte-vaisseaux de l\'Envahisseur déploient des Corvettes, augmentez le nombre de Corvettes ci-dessus.',
        returnTradeTokenDrones: 'Rendre le jeton de commerce (Drones)?',
        useBombard: 'Utiliser Bombardement (Nervo)?',
        bombardApproachAbs: 'Approche de Bombardement Abs',
        bombardSalvoAbs: 'Absorption de Salve de Bombardement',
        spendEnergyDSM: 'Dépenser 1 Énergie (Missiles Longue Portée)?',
        adjacentSectorsWithShipyards: 'Secteurs Adjacents avec Chantier Naval',
        adjacentSectorsWithStarbases: 'Secteurs Adjacents avec Base Stellaire',
        initiativeWarCard: '+5 Initiative (carte de Guerre)',
        approachAbsWarCard: '+1 Absorption d\'Approche (carte de Guerre)',
        salvoAbsWarCardEasy: '+1 Absorption de Salve (carte de Guerre - Facile)',
        salvoAbsWarCardHard: '+2 Absorption de Salve (carte de Guerre - Normal/Difficile)',
        salvoAbsCycle2EventH: '+X Absorption de Salve (Cycle 2 - Événement H)',
        calculateOutcomes: 'Calculer les Résultats',
        swap: 'Échanger',
        multipleOutcomes: 'NOTE : Il y a plusieurs résultats possibles. Vérifiez les détails pour déterminer lequel se produira dans votre jeu.',
        collapse: 'Réduire',
        share: 'Partager',
        combatSummaryCopied: 'Résumé du combat copié dans le presse-papiers.',
        invaderWins: 'L\'Envahisseur (${0}) Gagne',
        finalFleet: 'Flotte Finale (v${0})',
        combatVersion: 'Combat v${0}',
        approach: 'Approche',
        salvo: 'Salve'
    },
    "de": {
        scenarioTutorial: 'Tutorial',
        scenarioS01: 'Erste Instanz',
        scenarioS02: 'Eines Für Alle',
        scenarioS03: 'Dunkelste Stunde',
        scenarioS04: 'Antike Geheimnisse',
        scenarioS05: 'Teufelsdreieck',
        scenarioS06: 'Verblasende Finsternis',
        scenarioS07: 'Noch Nicht Heute',
        scenarioS08: 'Niedergang Der Zivilisation',
        scenarioC01: 'Zweite Genesis',
        scenarioC02: 'Für Frieden und Wohlstand',
        scenarioC03: 'Grundlagen der Zukunft',
        scenarioC04: 'Vermächtnis der Novarchen',
        scenarioC05: 'Kriegskunst',
        scenarioC06: 'Schicksalsstrudel',
        scenarioC07: 'Durch Die Veränderten Weiten',
        scenarioC08: 'Echos der Vergangenheit',
        scenarioC09: 'Bastion Des Widerstands',
        scenarioC10: 'Aufstieg Des Königreichs',
        scenarioC11: 'Frakturen Im All',
        techCybernetics: 'Autonome Drohnen',
        techCombatReplicators: 'Datenraffinerie',
        techDreadnoughts: 'Bergungsscanner',
        techDecontaminationChambers: 'Dekontaminationskammern',
        techNeuralMatrix: 'Energiezellen',
        techTerraforming: 'Hyperantrieb',
        techEscapePods: 'Handelsnexus',
        techShields: 'Kampfreplikatoren',
        techHyperdrive: 'Klonen',
        techTacticalTransports: 'Kybernetik',
        techCloning: 'Kolonieschiffe',
        techDestroyers: 'Läuterer',
        techArkShips: 'Orbitale Häfen',
        techCarriers: 'Robotik',
        techAutonomousDrones: 'Schilde',
        techCentralSurveillance: 'Sternenbasen',
        techDataRefinery: 'Schlächter',
        techDeepSpaceMissiles: 'Taktische Transporte',
        techEnergyCells: 'Terraformen',
        techSentries: 'Träger',
        techStarbases: 'Torpedos',
        techTargeting: 'Wächter',
        techTorpedoes: 'Weltraumgeschosse',
        techTradeNexus: 'Zerstörer',
        techCentralSurveillance: 'Zentrale Überwachung',
        techTargeting: 'Zielerfassung'
    }
}